services:
  - type: web
    name: prince-mdxi-bot
    env: node
    plan: free
    buildCommand: npm install
    startCommand: npm start
    autoDeploy: true
    envVars:
      - key: SESSION_ID
        value: "your-session-id"
      - key: MODE
        value: "private"
      - key: AUTO_READ_STATUS
        value: "true"
      - key: AUTO_REPLY
        value: "false"
      - key: ALIVE_IMG
        value: "https://img12.pixhost.to/images/856/575170607_skyzopedia.jpg"
      - key: MENU_IMG
        value: "https://files.catbox.moe/kzfne8.jpeg"
      - key: PREFIX
        value: "."
      - key: OMDB_API_KEY
        value: "your-omdb-api-key"
